<footer class="contact-footer">
  <ul class="contact-links">
    <li>
      <a href="https://calendar.app.google/zgkCUYzKk2jdng516" target="_blank" title="Google Calendar">
        <!-- Google Calendar Icon as Inline SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21 20V6c0-1.103-.897-2-2-2h-2V2h-2v2H9V2H7v2H5c-1.103 0-2 .897-2 2v14c0 1.103.897 2 2 2h14c1.103 0 2-.897 2-2M9 18H7v-2h2zm0-4H7v-2h2zm4 4h-2v-2h2zm0-4h-2v-2h2zm4 4h-2v-2h2zm0-4h-2v-2h2zm2-5H5V7h14z"/></svg>
        Schedule a Chat
      </a>
    </li>
    <li>
      <a href="mailto:wilson@mechanicalscribe.com" title="Email">
        <!-- Email Icon as Inline SVG -->
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2m-.4 4.25l-7.07 4.42c-.32.2-.74.2-1.06 0L4.4 8.25a.85.85 0 1 1 .9-1.44L12 11l6.7-4.19a.85.85 0 1 1 .9 1.44"/></svg>
wilson@mechanicalscribe.com
      </a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/chriswilsondc/" target="_blank" title="LinkedIn">
        <!-- LinkedIn Icon as Inline SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M22 2H2C1.447 2 1 2.447 1 3v18c0 .553.447 1 1 1h20c.553 0 1-.447 1-1V3c0-.553-.447-1-1-1zm-14 16H5v-9h3v9zm-1.5-10.5c-.947 0-1.5-.5-1.5-1.5s.553-1.5 1.5-1.5c.948 0 1.5.5 1.5 1.5s-.552 1.5-1.5 1.5zm10.5 10.5h-3v-5.5c0-1.25-.625-1.5-1.125-1.5-.625 0-1.125.375-1.125 1.5v5.5h-3v-9h3v1.25c.375-.875 1.25-1.25 2.25-1.25 1.5 0 3 1.5 3 4v4.5z"></path></svg>
        LinkedIn
      </a>
    </li>
  </ul>
  <p>&copy; 2025 Chris Wilson / Mechanical Scribe LLC. All Rights Reserved.</p>
  <div id="referring_note"></div>
</footer>
